#
# JavaBean Tester (https://github.com/hazendaz/javabean-tester)
#
# Copyright 2012-2020 Hazendaz.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of The Apache Software License,
# Version 2.0 which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0.txt
#
# Contributors:
#     CodeBox (Rob Dawson).
#     Hazendaz (Jeremy Landis).
#

name: Coveralls

on: [push, pull_request]

jobs:
  build:
    if: github.repository_owner == 'hazendaz'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Report Coverage to Coveralls for Pull Requests
        if: github.event_name == 'pull_request'
        run: ./mvnw -B -V test jacoco:report coveralls:report -q -Dlicense.skip=true -DrepoToken=$GITHUB_TOKEN -DserviceName=github -DpullRequest=$PR_NUMBER
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
      - name: Report Coverage to Coveralls for General Push
        if: github.event_name == 'push'
        run: ./mvnw -B -V test jacoco:report coveralls:report -q -Dlicense.skip=true -DrepoToken=$GITHUB_TOKEN -DserviceName=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
